<cfoutput>
    <cfmail to = "killion.kgs@gmail.com" from = "killion@kgs.ku.edu" replyto="killion@kgs.ku.edu" subject = "Oil-Gas Mapper Data Problem" type="html">
    	A user has reported a problem with the following feature:<p>
    	KGS ID: #form.id#<p>
    	<cfif #form.type# eq "field">
    		FIELD: #form.name#<p>
    	</cfif>
    	MESSAGE: #form.msg#<p>
    	*** this message is auto-generated by the oil and gas mapper ***
	</cfmail>
</cfoutput>
